Refactored to use latest version (0.3) of snmpd-connector-lib.

diff --git a/usr/sbin/snmpd-smartctl-connector b/usr/sbin/snmpd-smartctl-connector
--- a/usr/sbin/snmpd-smartctl-connector
+++ b/usr/sbin/snmpd-smartctl-connector
@@ -1,8 +1,8 @@
 #!/bin/bash -u
 
 # Include snmpd-connector-lib.sh or die.
-[[ ! -r /usr/lib/snmpd-connector-lib.sh ]] && echo "Unable to find /usr/lib/snmpd-connector-lib.sh" && exit 1
-source /usr/lib/snmpd-connector-lib.sh
+[[ ! -r ${SNMPD_CONNECTOR_LIB:=/usr/lib/snmpd-connector-lib.sh} ]] && echo "Unable to find ${SNMPD_CONNECTOR_LIB}" && exit 1
+source ${SNMPD_CONNECTOR_LIB}
 
 # Helper function to get the device path from the devices array using a 1 based index
 #
@@ -136,51 +136,49 @@ function send_device_attr
 
 # Function to get the next index value
 #
-#	@in_param	$2 - The base OID this is a request for
-#	@in_param	$+ - An array containing the request elements
+#	@in_param	$1 - The (optional) starting index value
+#	@echo		   - The new index or nothing if out of range
 #
 function get_next_index
 {
-	local RETVAL
-	
 	debug_function_enter "get_next_index" ${@}
 	
 	# If we still have more than one element in the request array then something
 	# is wrong so log an error and return 0.
-	if (( $# > 2 )); then
-		error_echo "get_next_index: called with $(( $# - 1 )) request array elements!"
-		debug_function_return 0
-		return 0
-	fi
-
-	# If we passed an index...
 	if (( $# > 1 )); then
+		error_echo "get_next_index: called with $# request array elements!"
+		debug_function_return
+		return
+	fi
+	
+	# If we were passed a starting index...
+	if (( $# > 0 )); then
 		# If the passed index is less than the number of devices then return it +1,
 		# otherwise return 0 to indicate that the index would be out of range. 
-		if (( ${2} < ${#DEVICES[@]} )); then
-			RETVAL=$(( ${2} + 1 ))
+		if (( ${1} < ${#DEVICES[@]} )); then
+			RETVAL=$(( ${1} + 1 ))
 			debug_echo "next index is in range, returning ${RETVAL}"
-			debug_function_return ${RETVAL}
-			return ${RETVAL}
+			echo "${RETVAL}"
+			debug_function_return
+			return
 		else
 			debug_echo "next index would be out of range, returning zero"
-			debug_function_return 0
-			return 0
+			debug_function_return
+			return
 		fi 
 	fi	
 	
 	# If we got this far then we were not passed an index so return the first
 	# available index.
 	debug_echo "no index supplied, returning first index"
-	debug_function_return 1
-	return 1
+	echo "1"
+	debug_function_return
+	return
 }
 
 # Init local vars
 CMDNAME=$(basename ${0})
 CONFIG="/etc/snmpd-smartctl-connector"
-DEBUG=""
-LOGGING=""
 DEVICES=""
 CACHEDIR=""
 SNMP_TRANSLATE=""
@@ -198,30 +196,26 @@ SNMP_TRANSLATE=""
 # Configure base address
 BASE_MIB="SMARTCTL-MIB::smartCtl"
 
-# Declare the root table
+# Declare the tables
 RTABLE[2]="#ETABLE"
-
-# Declare the E[ntry]TABLE
-ETABLE[1]="#FTABLE"
-
-# Declare the function table.
-FTABLE[0]="get_next_index"									# Internal function to get next index
-FTABLE[1]="send_index"										# It is an index request.
-FTABLE[2]="send_device_path" 								# It is for the mapped device path.
-FTABLE[3]="send_device_info 'Model Family:'" 				# It is for the device model-family.
-FTABLE[4]="send_device_info 'Device Model:'"				# It is for the device device-model.
-FTABLE[5]="send_device_info 'Serial Number:'" 				# It is for the device serial number.
-FTABLE[6]="send_device_info 'User Capacity:'" 				# It is for the device user capacity.
-FTABLE[7]="send_device_info 'ATA Version is:'"				# It is for the device ATA version.
-FTABLE[8]="send_device_hlth"								# It is for the overall SMART health state.
-FTABLE[9]="send_device_attr 'Temperature_Celsius' R" 		# It is for the device temperature.
-FTABLE[10]="send_device_attr 'Reallocated_Sector_Ct' R" 	# It is for the Reallocated Sector Count of this device.
-FTABLE[11]="send_device_attr 'Current_Pending_Sector' R"	# It is for the Current Pending Sector count of this device.
-FTABLE[12]="send_device_attr 'Offline_Uncorrectable' R" 	# It is for the Off-line Uncorrectable count of this device.
-FTABLE[13]="send_device_attr 'UDMA_CRC_Error_Count' R" 		# It is for the UDMA CRC Error count of this device.
-FTABLE[14]="send_device_attr 'Read_Error_Rate' L" 			# It is for the Read Error Rate (lifetime) of this device.
-FTABLE[15]="send_device_attr 'Seek_Error_Rate' L"	 		# It is for the Seek Error Rate (lifetime) of this device.
-FTABLE[16]="send_device_attr 'Hardware_ECC_Recovered' L" 	# It is for the Hardware ECC recovered (lifetime) of this device.
+	ETABLE[1]="#FTABLE"
+		FTABLE_INDEX="get_next_index"								# Internal function to get next index
+		FTABLE[1]="send_index"										# It is an index request.
+		FTABLE[2]="send_device_path" 								# It is for the mapped device path.
+		FTABLE[3]="send_device_info 'Model Family:'" 				# It is for the device model-family.
+		FTABLE[4]="send_device_info 'Device Model:'"				# It is for the device device-model.
+		FTABLE[5]="send_device_info 'Serial Number:'" 				# It is for the device serial number.
+		FTABLE[6]="send_device_info 'User Capacity:'" 				# It is for the device user capacity.
+		FTABLE[7]="send_device_info 'ATA Version is:'"				# It is for the device ATA version.
+		FTABLE[8]="send_device_hlth"								# It is for the overall SMART health state.
+		FTABLE[9]="send_device_attr 'Temperature_Celsius' R" 		# It is for the device temperature.
+		FTABLE[10]="send_device_attr 'Reallocated_Sector_Ct' R" 	# It is for the Reallocated Sector Count of this device.
+		FTABLE[11]="send_device_attr 'Current_Pending_Sector' R"	# It is for the Current Pending Sector count of this device.
+		FTABLE[12]="send_device_attr 'Offline_Uncorrectable' R" 	# It is for the Off-line Uncorrectable count of this device.
+		FTABLE[13]="send_device_attr 'UDMA_CRC_Error_Count' R" 		# It is for the UDMA CRC Error count of this device.
+		FTABLE[14]="send_device_attr 'Read_Error_Rate' L" 			# It is for the Read Error Rate (lifetime) of this device.
+		FTABLE[15]="send_device_attr 'Seek_Error_Rate' L"	 		# It is for the Seek Error Rate (lifetime) of this device.
+		FTABLE[16]="send_device_attr 'Hardware_ECC_Recovered' L" 	# It is for the Hardware ECC recovered (lifetime) of this device.
 
 # Start the loop
 the_loop
